In [2]:
import numpy as np;


In [4]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[0,1]=6
a

array([[1, 6, 3],
       [4, 5, 6]])

In [9]:
a.size

6

In [10]:
a.shape

(2, 3)

In [12]:
a[0][0]

1

In [ ]:
a = np.array([1,2,3])

In [13]:
a.dtype

dtype('int64')

In [15]:
d=np.array([1,2,3,45,'t','u','o','k'])
d

array(['1', '2', '3', '45', 't', 'u', 'o', 'k'], dtype='<U21')

In [19]:
d[4]

't'

In [20]:
d[5]='p'
d

array(['1', '2', '3', '45', 't', 'p', 'o', 'k'], dtype='<U21')

In [21]:
d.dtype

dtype('<U21')

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

In [24]:
m=np.zeros((5,5))
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
m.dtype

dtype('float64')

In [28]:
k=np.ones((6,6))
k

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
for i in range(2,45,2):
  print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
f=np.arange(1,100,5)
f

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [36]:
n=np.linspace(1,56,12)
n

array([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46., 51., 56.])

In [38]:
d=np.empty((5,2))
d

array([[4.81357889e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.79218869e+160],
       [4.99026973e+174, 5.33602592e-091],
       [1.61541723e+160, 4.67430838e-315]])

In [43]:
h=np.identity(5)
h

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[2,1,1]])

In [45]:
l=np.arange(1,200)
l

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [47]:
np.reshape(4,50)

ValueError: ignored

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
a.sum(axis=0)

array([12, 15, 18])

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.flat
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
for i in a.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
e=a.ravel()#flat value of array
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in e:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.ndim

2

In [ ]:
b=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4],[7,5,3,4]]])
b

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 8, 9, 4],
        [7, 5, 3, 4]]])

In [ ]:
b.ndim

3

In [ ]:
b.size

16

In [ ]:
b.shape#dought

(1, 4, 4)

In [ ]:
a.shape

(3, 3)

In [ ]:
a.nbytes

72

In [ ]:
b.nbytes

128

In [ ]:
b.argmax()


10

In [ ]:
a.argmin()

0

In [ ]:
b.argsort()# provide index in increasing order

array([[[0, 1, 2, 3],
        [0, 1, 2, 3],
        [3, 0, 1, 2],
        [2, 3, 1, 0]]])

In [ ]:
a.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a.argmax(axis=0)

array([2, 2, 2])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 1, 1]])

In [ ]:
a.argmax(axis=1)#provide index of max value

array([2, 2, 0])

In [ ]:
a.sort()#provide value in sort

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 2]])

In [ ]:
m=np.array([1,2,3,4,5,6,7,8,9,10])
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [1],
       [1],
       [2]])

In [ ]:
b=np.array([[1,2,2],[4,5,6]])
b

array([[1, 2, 2],
       [4, 5, 6]])

In [ ]:
a

[[1, 2, 2], [4, 5, 6]]

In [ ]:
a+b

array([[ 2,  4,  4],
       [ 8, 10, 12]])

In [ ]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a*b

array([[ 1,  4,  4],
       [16, 25, 36]])

In [ ]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b.sum()

79

In [ ]:
b.min()

1

In [ ]:
b.max()

9

In [ ]:
np.count_nonzero(b)

16

In [ ]:
import numpy as np;

In [ ]:
a=np.arange(6,)
a2=a[np.newaxis,:]
a2


array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
b=np.array([[1,2,3,4],[4,5,6,2],[7,8,9,5]])
b[0]

array([1, 2, 3, 4])

In [ ]:
b.shape

(3, 4)

In [ ]:
b[2,3]

5

In [ ]:
np.zeros((9,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty(6)

array([4.83181924e-310, 0.00000000e+000, 6.56371261e-310, 1.63041663e-322,
       4.83298274e-310, 6.56377589e-310])

In [ ]:
np.arange(6)#max range

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(1,10,2)#start stop and space

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [ ]:
b=np.ones(3,dtype=np.int32)
b

array([1, 1, 1], dtype=int32)

In [ ]:
m=np.zeros(4, dtype=np.float32)
m

array([0., 0., 0., 0.], dtype=float32)

In [ ]:
m.nbytes

16